sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t 273838393/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true 273838393/react-test npm test

after_success:
  - docker build -t 273838393/multi-client ./client
  - docker build -t 273838393/multi-nginx ./nginx
  - docker build -t 273838393/multi-server ./server
  - docker build -t 273838393/multi-worker ./worker
  #push to docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push 273838393/multi-client
  - docker push 273838393/multi-nginx
  - docker push 273838393/multi-server
  - docker push 273838393/multi-worker
